---
- name: TLS certificate
  when: >
    radicale_self_signed_certificate is undefined
    or not radicale_self_signed_certificate
  notify: Restart radicale
  tags:
    - cert
  block:
    - name: Setting certificate directory
      ansible.builtin.set_fact:
        radicale_certificate_dir:
          "{{ inventory_dir }}/../../certs/{{ radicale_domain }}"
      when: >
        radicale_certificate_dir is undefined
        or not radicale_certificate_dir

    - name: Setting certificate fullchain
      ansible.builtin.set_fact:
        radicale_certificate_fullchain:
          "{{ radicale_certificate_dir }}/fullchain.pem"

    - name: "Debug certificate_fullchain"
      ansible.builtin.debug:
        var: radicale_certificate_fullchain

    - name: Setting certificate key path
      ansible.builtin.set_fact:
        radicale_certificate_privkey:
          "{{ radicale_certificate_dir }}/privkey.pem"

    - name: "Debug radicale_self_signed_certificate"
      ansible.builtin.debug:
        var: radicale_self_signed_certificate

    - name: "Copy certificate to remote host"
      ansible.builtin.copy:
        src: "{{ radicale_certificate_fullchain }}"
        dest: "/etc/ssl/{{ radicale_domain }}.crt"
        owner: root
        group: "{{ radicale_group_ssl }}"
        mode: "0640"
      notify: Restart radicale

    - name: "Copy private key to remote host"
      ansible.builtin.copy:
        src: "{{ radicale_certificate_privkey }}"
        dest: "/etc/ssl/private/{{ radicale_domain }}.key"
        mode: "0640"
        owner: root
        group: "{{ radicale_group_ssl }}"
      notify: Restart radicale


- name: Generate a Self Signed OpenSSL certificate
  ansible.builtin.shell: |
    openssl genrsa -out "{{ radicale_tls_private_key }}" 4096
    openssl req -new -x509 \
      -key "{{ radicale_tls_private_key }}" \
      -out "{{ radicale_tls_certificate }}" -days 3650 \
      -subj "/C=US/ST=Example/L=Example/O=Dis/CN={{ radicale_domain }}"
  when:
    - radicale_self_signed_certificate is defined
    - (radicale_self_signed_certificate)
  changed_when: false
  notify: Restart radicale

- name: Adjust private key owner and access
  ansible.builtin.file:
    path: "{{ radicale_tls_private_key }}"
    mode: "0640"
    owner: root
    group: "{{ radicale_group_ssl }}"
  notify: Restart radicale
