---
- name: TLS certificate
  when: >
    radicale_self_signed_certificate is undefined
    or not radicale_self_signed_certificate
  notify: Restart radicale
  tags:
    - cert
  block:
    - name: Setting certificate directory
      set_fact:
        radicale_certificate_dir:
          "{{ inventory_dir }}/../../certs/{{ radicale_domain }}"
      when: >
        radicale_certificate_dir is undefined
        or not radicale_certificate_dir

    - name: Setting certificate fullchain
      set_fact:
        radicale_certificate_fullchain:
          "{{ radicale_certificate_dir }}/fullchain.pem"

    - name: "Debug certificate_fullchain"
      debug:
        var: radicale_certificate_fullchain

    - name: Setting certificate key path
      set_fact:
        radicale_certificate_privkey:
          "{{ radicale_certificate_dir }}/privkey.pem"

    - name: "Debug radicale_self_signed_certificate"
      debug:
        var: radicale_self_signed_certificate

    - name: "Copy certificate to remote host"
      copy:
        src: "{{ radicale_certificate_fullchain }}"
        dest: "/etc/ssl/{{ radicale_domain }}.crt"
        mode: "0640"
      notify: Restart radicale

    - name: "Copy private key to remote host"
      copy:
        src: "{{ radicale_certificate_privkey }}"
        dest: "/etc/ssl/private/{{ radicale_domain }}.key"
        mode: "0640"
        owner: root
        group: "{{ radicale_group_ssl }}"
      notify: Restart radicale
      tags:
        - cert
        - notest

- name: Generate a Self Signed OpenSSL certificate
  shell: |
    openssl genrsa -out "/etc/ssl/private/{{ radicale_domain }}.key" 4096
    openssl req -new -x509 \
      -key "/etc/ssl/private/{{ radicale_domain }}.key" \
      -out "/etc/ssl/{{ radicale_domain }}.crt" -days 365 \
      -subj "/C=US/ST=Example/L=Example/O=Dis/CN={{ radicale_domain }}"
  when:
    - radicale_self_signed_certificate is defined
    - (radicale_self_signed_certificate)
  notify: Restart radicale
