---
- name: Ensure resolv.conf is mutable before changing it
  file:
    path: /etc/resolv.conf
    attr: -i
  register: resolv_file
    # changed_when: "'i' in resolv_file.diff.before.attributes"
    #
- name: debug resolv_file
  debug:
    var: resolv_file

- name: Create /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure resolv.conf is immutable
  file:
    path: /etc/resolv.conf
    attr: +i
  register: resolv_file
  changed_when: "'i' not in resolv_file.diff.before.attributes"
