---

- name: "include tasks from certificate.yml"
  include_tasks:
    file: certificate.yml
    apply:
      tags:
        - cert
  tags:
    - cert

- name: "Put TLS cert to {{ radicale_tls_certificate }}"
  copy:
    src: "{{ certificate_fullchain }}"
    dest: "{{ radicale_tls_certificate }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - cert
  notify: restart radicale

- name: "Put TLS certificate private {{ radicale_tls_private_key }}"
  copy:
    src: "{{ certificate_privkey }}"
    dest: "{{ radicale_tls_private_key }}"
    owner: root
    group: "{{ radicale_group_ssl }}"
    mode: 0640
  tags:
    - cert
  notify: restart radicale

- name: add user {{ radicale_user }} to group {{ radicale_group_ssl }}
  user:
    name: "{{ radicale_user }}"
    groups: "{{ radicale_group_ssl }}"
    append: true

- name: create directory {{ radicale_pidfile | dirname }}
  file:
    path: "{{ radicale_pidfile | dirname }}"
    state: directory

- name: create directory /var/lib/radicale
  file:
    path: /var/lib/radicale
    state: directory
    owner: "{{ radicale_user }}"
    group: "{{ radicale_group }}"

# filesystem_folder = /var/lib/radicale/collections

- name: install radicale
  package:
    name:
      - python3-radicale
      - radicale

- name: enable radicale
  lineinfile:
    path: /etc/default/radicale
    line: "ENABLE_RADICALE=yes"
    regex: "^#ENABLE_RADICALE"

- name: Create /etc/radicale/config
  template:
    src: config.j2
    dest: /etc/radicale/config
    owner: root
    group: root
    mode: '0644'
  notify: restart radicale

- name: Create systemd service file
  template:
    src: radicale.service.j2
    dest: /etc/systemd/system/radicale.service
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
    - restart radicale

- name: Enable radicale service
  systemd:
    name: radicale
    enabled: true
