---
- name: Create group  {{ radicale_group_ssl }}
  ansible.builtin.group:
    name: '{{ radicale_group_ssl }}'
    system: true

- name: Add radicale user to group {{ radicale_group_ssl }}
  ansible.builtin.user:
    name: "{{ radicale_user }}"
    groups: "{{ radicale_group_ssl }}"
    append: true

- name: Include tasks from certificate.yml
  ansible.builtin.include_tasks:
    file: certificate.yml
    apply:
      tags:
        - cert
  tags:
    - cert
    - notest

# TODO delete
# - name: Create directory {{ radicale_pidfile | dirname }}
#   ansible.builtin.file:
#     path: "{{ radicale_pidfile | dirname }}"
#     state: directory
#     owner: root
#     mode: 0755

- name: Create directory /var/lib/radicale
  ansible.builtin.file:
    path: /var/lib/radicale
    state: directory
    owner: "{{ radicale_user }}"
    group: "{{ radicale_group }}"
    mode: 0755

- name: Only run "update_cache=yes" if the last one is more than 100h ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 360000

- name: Install required packages
  ansible.builtin.package:
    name:
      - python3-radicale
      - python3-passlib
      - radicale
      - nginx

- name: Enable radicale
  ansible.builtin.lineinfile:
    path: /etc/default/radicale
    line: "ENABLE_RADICALE=yes"
    regex: "^#ENABLE_RADICALE"

- name: Create /etc/radicale/config
  ansible.builtin.template:
    src: config.j2
    dest: /etc/radicale/config
    owner: root
    group: root
    mode: 0644
  notify: Restart radicale

- name: Create systemd service file
  ansible.builtin.template:
    src: radicale.service.j2
    dest: /etc/systemd/system/radicale.service
    mode: 0644
    owner: root
    group: root
  notify:
    - Reload systemd
    - Restart radicale

- name: Enable radicale service
  ansible.builtin.systemd:
    name: radicale
    enabled: true

- name: Create radicale users
  community.general.htpasswd:
    path: /etc/radicale/users
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: "{{ radicale_user }}"
    group: "{{ radicale_group }}"
    mode: 0640
  with_items: "{{ radicale_user_list }}"
  when:
    - radicale_user_list is defined
    - (radicale_user_list)
