---
driver:
  name: docker

platforms:
  - name: instance
    image: "ghcr.io/sv0/${MOLECULE_DISTRO:-debian-13-systemd}:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp

verifier:
  name: testinfra
